controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login:
    path: /api/login
    methods: ['POST']
api_refresh_token:
    path: /api/token/refresh
